name: Build and Publish notarizer to PyPI

on:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Unit Tests
      run: |
        make unit-tests
    - name: Linter
      run: |
        make lint
    - name: Code Style
      run: |
        make codestyle
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Get the version
      id: get_version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/releases\//}" >> $GITHUB_ENV
        echo $RELEASE_VERSION
    - name: Dependencies
      run: |
        make install-dev
    - name: Generate binaries
      run: |
        make package