name: Build and Publish notarizer to PyPI

on:
  push:
    tags:
      - 'releases/[1-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Unit Tests
      run: |
        make unit-tests
    - name: Linter
      run: |
        make lint
    - name: Code Style
      run: |
        make codestyle
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Get the version
      if: startsWith( github.ref, 'refs/tags/releases/')
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Dependencies
      run: |
        make install-dev
    - name: Generate binaries
      run: |
        make package
    - name: Publish distribution package to PyPI
      if: startsWith( github.ref, 'refs/tags/releases/')
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{ secrets.PYPI_TOKEN }}