name: Build and Publish notarizer to PyPI

on:
  push:
    tags:
      - 'releases-beta/[1-9]+.[0-9]+.[0-9]+b'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Unit Tests
      run: |
        make unit-tests
    - name: Linter
      run: |
        make lint
    - name: Code Style
      run: |
        make codestyle
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Get the version
      if: startsWith( github.ref, 'refs/tags/releases-beta/')
      id: get_version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/releases-beta/}" >> $GITHUB_ENV
    - name: Test Version Extraction
      if: startsWith( github.ref, 'refs/tags/releases-beta/')
      run: echo $RELEASE_VERSION
    - name: Dependencies
      run: |
        make install-dev
    - name: Generate binaries
      run: |
        make package